# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="random"
ZSH_THEME="ys"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  wd
  zsh-syntax-highlighting
  zsh-autosuggestions
)

source ${ZSH}/oh-my-zsh.sh
#source ${ZSH}/custom/plugins/incr/incr.zsh

[[ -s ${HOME}/.autojump/etc/profile.d/autojump.sh ]] && source ${HOME}/.autojump/etc/profile.d/autojump.sh

autoload -U compinit && compinit -u

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias ls='ls $LS_OPTIONS --color=auto'
alias ll='ls $LS_OPTIONS -l --color=auto'
alias l='ls $LS_OPTIONS -lA --color=auto'
alias la='ls $LS_OPTIONS -alF --color=auto'

alias vi="vim"
alias doim="docker image"
alias dops="docker ps"
alias dpa="docker ps -a"
alias doco="docker-compose"
alias dcud="docker-compose up -d"
alias dcdo="docker-compose down"
alias dcps="docker-compose ps"
alias de='doex() { sudo docker exec -it $1 /bin/bash; }; doex'
alias pag='psauxgrep() { echo "sudo ps aux | grep $1"; sudo ps aux | grep $1 }; psauxgrep'

# Linux历史命令保留10000条
HISTFILESIZE=10000

if [[ -d ${HOME}/.myenv ]]; then
  for i in ${HOME}/.myenv/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi

#[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

FZF_HOME=${HOME}/.fzf
# Setup fzf
# ---------
if [[ ! "$PATH" == *${FZF_HOME}/bin* ]]; then
  PATH="${PATH:+${PATH}:}${FZF_HOME}/bin"
fi

# Auto-completion
# ---------------
[[ $- == *i* ]] && [[ ${FZF_HOME}/shell/completion.zsh ]] && source "${FZF_HOME}/shell/completion.zsh" 2> /dev/null

MY_CONF=/opt/workspace/github/myconf
if [[ -f ${MY_CONF}/shell/global_environment/myenv.sh ]]; then
    source ${MY_CONF}/shell/global_environment/myenv.sh
fi

if [[ -f ${MY_CONF}/shell/global_environment/myalias.sh ]]; then
    source ${MY_CONF}/shell/global_environment/myalias.sh
fi

# Key bindings
# ------------
[ ${FZF_HOME}/shell/key-bindings.zsh ] && source "${FZF_HOME}/shell/key-bindings.zsh"

# 配置gvim主题可以在终端下完美显示
export TERM=xterm-256color
# Linux历史命令保留10000条
HISTFILESIZE=10000

export XMODIFIERS=@im=yong
export GTK_IM_MODULE=yong
export QT_IM_MODULE=yong

export http_proxy='127.0.0.1:7890'
export https_proxy='127.0.0.1:7890'
